
--
-- Data for table `tau_translations`
--

INSERT INTO `tau_translations` ( `lang`, `t_group`, `item`, `content`) VALUES
( 'es', 'lang_labels', 'LU_ACTIONS', 'Acciones'),
( 'es', 'lang_labels', 'LU_MODIFY', 'Modificar'),
( 'es', 'lang_labels', 'LU_DELETE', 'Eliminar'),
( 'es', 'lang_labels', 'LU_LAST_F', 'Última'),
( 'es', 'lang_labels', 'LU_FIRST_F', 'Primera'),
( 'es', 'lang_labels', 'LU_PRIOR', '&lt; Anterior'),
( 'es', 'lang_labels', 'LU_NEXT', '&gt; Siguiente'),
( 'es', 'lang_labels', 'LU_NUM_REGISTERS_FOUND', 'Número de registros encontrados'),
( 'es', 'lang_labels', 'LU_SHOWN_PAGES', 'Se muestran páginas de'),
( 'es', 'lang_labels', 'LU_REGISTERS', 'registros cada una'),
( 'es', 'lang_labels', 'LU_SHOWN_THE_PAGE', 'Mostrando la página'),
( 'es', 'lang_labels', 'LU_OF', 'de'),
( 'es', 'lang_labels', 'LU_FIELD', 'Campo'),
( 'es', 'lang_labels', 'LU_VALUE', 'Valor'),
( 'es', 'lang_labels', 'LU_INIT_SESSION', 'Iniciar Sesión'),
( 'es', 'lang_labels', 'LU_USER', 'Usuario'),
( 'es', 'lang_labels', 'LU_PASSWORD', 'Password'),
( 'es', 'lang_labels', 'LU_REGS', 'registros'),
( 'es', 'lang_labels', 'LU_FORGOT_PASS', '¿ Has olvidado tu contraseña ?'),
( 'es', 'lang_labels', 'LU_CONTACT', 'Contactar'),
( 'es', 'lang_labels', 'LU_WPAGES', ' páginas'),
( 'es', 'lang_labels', 'LU_IN', 'en'),
( 'es', 'lang_labels', 'LU_REMEMBER_ME', ' Recordarme en este equipo'),
( 'es', 'lang_labels', 'LU_VALIDATE', 'Validar'),
( 'es', 'lang_labels', 'LU_MODIFICATION_OK', 'Modificación correcta'),
( 'es', 'lang_labels', 'LU_INSERT_OK', ' Inserción correcta'),
( 'es', 'lang_labels', 'LU_DELETE_OK', ' Eliminación correcta. '),
( 'es', 'lang_labels', 'LU_AFFECTED_ROWS', ' valores fueron eliminados'),
( 'es', 'lang_labels', 'LU_NICKNAME_ALLOWED_CHARS', 'Caracteres permitidos: Letras (may&uacute;sculas y min&uacute;sculas), n&uacute;meros y el caracter \'_\' '),
( 'es', 'lang_labels', 'LU_VALIDATED', ' validado'),
( 'es', 'lang_labels', 'LU_YET_VALIDATED_LIKE', ' Ya est&aacute; validado como'),
( 'es', 'lang_labels', 'LU_IF_NEW_SESSION', 'si desea comenzar otra sesi&oacute;n'),
( 'es', 'lang_labels', 'LU_MUST_END_THIS', 'debe finalizar esta primero'),
( 'es', 'lang_labels', 'LU_END_SESSION', 'Finalizar sesi&oacute;n'),
( 'es', 'lang_labels', 'LU_SESSION_STARTED', 'El usuario y el password son correctos. Bienvenido/a a {replace_appname}'),
( 'es', 'lang_labels', 'LU_SESSION_ERROR', 'El usuario o el password no son correctos. Si el problema persiste, póngase en contacto con nosotros.'),
( 'es', 'lang_labels', 'LU_SESSION_FINISHED', ' Sesión terminada. Gracias por utilizar nuestros servicios'),
( 'es', 'lang_labels', 'LU_CORRECT_REG_SEND_MAIL', ' Pre-registro correcto. Recibirá un e-mail con un link de confirmación para terminar de registrarse en la dirección que nos ha facilitado'),
( 'es', 'lang_labels', 'LU_SUCCESS_REGISTRATION', ' El registro ha finalizado con éxito. Diríjase al apartado de Login para iniciar sesión.'),
( 'es', 'lang_labels', 'LU_NO_RESULTS', ' No se encontraron resultados'),
( 'es', 'lang_labels', 'LU_MAIL_SENT_CONTACT', ' Su mensaje se ha enviado correctamente. En breve nos pondremos en contacto con usted.'),
( 'es', 'lang_labels', 'LU_NAME', 'Nombre'),
( 'es', 'lang_labels', 'LU_EMAIL', 'E-mail'),
( 'es', 'lang_labels', 'LU_NICK', 'Nick'),
( 'es', 'lang_labels', 'LU_SUBJECT', 'Asunto'),
( 'es', 'lang_labels', 'LU_CAPTCHA', 'Código'),
( 'es', 'lang_labels', 'LU_MESSAGE', 'Mensaje'),
( 'es', 'lang_labels', 'LU_RELOAD_IMAGE', 'Recargar imagen'),
( 'es', 'lang_labels', 'LU_CORRECT_DELETE_FILE', ' Se ha borrado el archivo '),
( 'es', 'lang_labels', 'LU_DID_YOU_FORGET_PASS', '¿ Has olvidado tu contraseña ?'),
( 'es', 'lang_labels', 'LU_PASS_FORGOT_TEXT', 'Si ha olvidado su contraseña, rellene estos datos y le será enviado un código de confirmación a su correo.'),
( 'es', 'lang_labels', 'LU_NEW_PASS', 'Nueva contraseña'),
( 'es', 'lang_labels', 'LU_SEND', 'Enviar'),
( 'es', 'lang_labels', 'LU_SAVE', 'Guardar'),
( 'es', 'lang_labels', 'LU_CONFIRM', 'Confirmar'),
( 'es', 'lang_labels', 'LU_SUBJECT_FORGOTTEN_PASS', 'Olvido contraseña'),
( 'es', 'lang_labels', 'LU_MAIL_SENT_PASS', ' Se le ha enviado un correo con un link para restablecer su contraseña. Revise su correo.'),
( 'es', 'lang_labels', 'LU_CORRECT_RESET_PASSWORD', ' Su contraseña ha sido cambiada'),
( 'es', 'lang_labels', 'LU_REGISTER_FORM', 'Formulario de registro'),
( 'es', 'lang_labels', 'LU_ALL_FIELDS_REQUIRED', 'Todos los campos son obligatorios'),
( 'es', 'lang_labels', 'LU_REGISTER', 'Registrarme'),
( 'es', 'lang_labels', 'MENU_HOME', 'Home'),
( 'es', 'lang_labels', 'MENU_REGISTER', 'Darse de Alta'),
( 'es', 'lang_labels', 'MENU_LEGAL', 'Aviso Legal'),
( 'es', 'lang_labels', 'MENU_DIRECTORY', 'Directorio'),
( 'es', 'lang_labels', 'MENU_HELP', 'Ayuda'),
( 'es', 'lang_labels', 'MENU_CONTACT', 'Contacto'),
( 'es', 'lang_labels', 'MENU_SEARCH', 'Búsqueda'),
( 'es', 'lang_labels', 'LU_YOUR_ACCOUNT', 'Su Cuenta'),
( 'es', 'lang_labels', 'LU_LANGLABEL', 'Idioma'),
( 'es', 'lang_labels', 'INDEX_DESCRIPTION', ''),
( 'es', 'lang_labels', 'FICHA_DESCRIPTION', 'Página de '),
( 'es', 'lang_labels', 'YET_SESSION_INIT', 'Ya ha iniciado sesión como <b>rep_nick</b>, debe '),
( 'es', 'lang_labels', 'END_SESS_LABEL', 'finalizar sesión'),
( 'es', 'lang_labels', 'GET_OUT', 'salir'),
( 'es', 'lang_labels', 'BEFORE_ENTER', ' antes de entrar en la página de registro'),
( 'es', 'lang_labels', 'PAGE_NOT_FOUND', ' Página no encontrada.'),
( 'es', 'lang_labels', 'START_SESSION', 'Iniciar Sesión'),
( 'es', 'lang_labels', 'END_SESSION', 'Cerrar Sesión'),
( 'es', 'lang_labels', 'TITLE_END_REGISTER', 'Darse de Alta - Fin'),
( 'es', 'lang_labels', 'TITLE_LOGIN', 'Iniciar Sesión'),
( 'es', 'lang_labels', 'TITLE_LOGOUT', 'Finalizar sesión'),
( 'es', 'lang_labels', 'TITLE_NEW_GALLERY', 'Crear galería o insertar fotos'),
( 'es', 'lang_labels', 'TITLE_SAVE_DATA', 'Guardar datos'),
( 'en', 'lang_labels', 'LU_ACTIONS', 'Actions'),
( 'en', 'lang_labels', 'LU_MODIFY', 'Modify'),
( 'en', 'lang_labels', 'LU_DELETE', 'Delete'),
( 'en', 'lang_labels', 'LU_LAST_F', 'Last'),
( 'en', 'lang_labels', 'LU_FIRST_F', 'First'),
( 'en', 'lang_labels', 'LU_PRIOR', '&lt; Previous'),
( 'en', 'lang_labels', 'LU_NEXT', '&gt; Next'),
( 'en', 'lang_labels', 'LU_NUM_REGISTERS_FOUND', 'Number of registers found'),
( 'en', 'lang_labels', 'LU_SHOWN_PAGES', 'Showing pages of'),
( 'en', 'lang_labels', 'LU_REGISTERS', 'registers each'),
( 'en', 'lang_labels', 'LU_SHOWN_THE_PAGE', 'Showing page'),
( 'en', 'lang_labels', 'LU_OF', 'of'),
( 'en', 'lang_labels', 'LU_FIELD', 'Field'),
( 'en', 'lang_labels', 'LU_VALUE', 'Value'),
( 'en', 'lang_labels', 'LU_INIT_SESSION', 'Start Session'),
( 'en', 'lang_labels', 'LU_USER', 'User'),
( 'en', 'lang_labels', 'LU_PASSWORD', 'Password'),
( 'en', 'lang_labels', 'LU_REGS', 'registers'),
( 'en', 'lang_labels', 'LU_FORGOT_PASS', 'Did you forgot your password ?'),
( 'en', 'lang_labels', 'LU_CONTACT', 'Contact'),
( 'en', 'lang_labels', 'LU_WPAGES', ' pages'),
( 'en', 'lang_labels', 'LU_IN', 'in'),
( 'en', 'lang_labels', 'LU_REMEMBER_ME', ' Remember me'),
( 'en', 'lang_labels', 'LU_VALIDATE', 'Validate'),
( 'en', 'lang_labels', 'LU_MODIFICATION_OK', 'Success modification'),
( 'en', 'lang_labels', 'LU_INSERT_OK', ' Success insertion'),
( 'en', 'lang_labels', 'LU_DELETE_OK', ' Success deleting. '),
( 'en', 'lang_labels', 'LU_AFFECTED_ROWS', ' values were deleted'),
( 'en', 'lang_labels', 'LU_NICKNAME_ALLOWED_CHARS', 'Allowed chars: Letters (lowercase and uppercase), numbers and character \'_\' '),
( 'en', 'lang_labels', 'LU_VALIDATED', ' validated'),
( 'en', 'lang_labels', 'LU_YET_VALIDATED_LIKE', ' Yet validated as'),
( 'en', 'lang_labels', 'LU_IF_NEW_SESSION', 'if you want to start another session'),
( 'en', 'lang_labels', 'LU_MUST_END_THIS', 'you must close this before'),
( 'en', 'lang_labels', 'LU_END_SESSION', 'End session'),
( 'en', 'lang_labels', 'LU_SESSION_STARTED', 'User and password are correct. Welcome to '),
( 'en', 'lang_labels', 'LU_SESSION_ERROR', 'The e-mail or password are incorrect. If the problem persists, please contact with us.'),
( 'en', 'lang_labels', 'LU_SESSION_FINISHED', ' End session. Thanks for using our services'),
( 'en', 'lang_labels', 'LU_CORRECT_REG_SEND_MAIL', ' Pre-register successful. You will get a mail with a confirmation link to end this registration.'),
( 'en', 'lang_labels', 'LU_SUCCESS_REGISTRATION', ' Registration success. Go to login to start a session.'),
( 'en', 'lang_labels', 'LU_NO_RESULTS', ' No results found'),
( 'en', 'lang_labels', 'LU_MAIL_SENT_CONTACT', ' Your message was sent successful. We\'ll contact you as soon as possible.'),
( 'en', 'lang_labels', 'LU_NAME', 'Name'),
( 'en', 'lang_labels', 'LU_EMAIL', 'E-mail'),
( 'en', 'lang_labels', 'LU_NICK', 'Nick'),
( 'en', 'lang_labels', 'LU_SUBJECT', 'Subject'),
( 'en', 'lang_labels', 'LU_CAPTCHA', 'Code'),
( 'en', 'lang_labels', 'LU_MESSAGE', 'Message'),
( 'en', 'lang_labels', 'LU_RELOAD_IMAGE', 'Reload image'),
( 'en', 'lang_labels', 'LU_CORRECT_DELETE_FILE', ' File deleted '),
( 'en', 'lang_labels', 'LU_DID_YOU_FORGET_PASS', 'Forgot your password ?'),
( 'en', 'lang_labels', 'LU_PASS_FORGOT_TEXT', 'If you forgot your password, fill this form and you will get a change password link in your mail.'),
( 'en', 'lang_labels', 'LU_NEW_PASS', 'New password'),
( 'en', 'lang_labels', 'LU_SEND', 'Send'),
( 'en', 'lang_labels', 'LU_SAVE', 'Save'),
( 'en', 'lang_labels', 'LU_CONFIRM', 'Confirm'),
( 'en', 'lang_labels', 'LU_SUBJECT_FORGOTTEN_PASS', 'Password forgotten'),
( 'en', 'lang_labels', 'LU_MAIL_SENT_PASS', ' We have sent you an e-mail to restablish your password. Look on your mail.'),
( 'en', 'lang_labels', 'LU_CORRECT_RESET_PASSWORD', ' Your password was restored'),
( 'en', 'lang_labels', 'LU_REGISTER_FORM', 'Register form'),
( 'en', 'lang_labels', 'LU_ALL_FIELDS_REQUIRED', 'All fields are mandatory'),
( 'en', 'lang_labels', 'LU_REGISTER', 'Register'),
( 'en', 'lang_labels', 'MENU_HOME', 'Home'),
( 'en', 'lang_labels', 'MENU_REGISTER', 'Register'),
( 'en', 'lang_labels', 'MENU_LEGAL', 'Legal advice'),
( 'en', 'lang_labels', 'MENU_DIRECTORY', 'Directory'),
( 'en', 'lang_labels', 'MENU_HELP', 'Help'),
( 'en', 'lang_labels', 'MENU_CONTACT', 'Contact'),
( 'en', 'lang_labels', 'MENU_SEARCH', 'Search'),
( 'en', 'lang_labels', 'LU_YOUR_ACCOUNT', 'Your Account'),
( 'en', 'lang_labels', 'LU_LANGLABEL', 'Language'),
( 'en', 'lang_labels', 'INDEX_DESCRIPTION', ''),
( 'en', 'lang_labels', 'FICHA_DESCRIPTION', 'Page of '),
( 'en', 'lang_labels', 'YET_SESSION_INIT', 'Yet logged as <b>rep_nick</b>, you must '),
( 'en', 'lang_labels', 'END_SESS_LABEL', 'end session'),
( 'en', 'lang_labels', 'GET_OUT', 'exit'),
( 'en', 'lang_labels', 'BEFORE_ENTER', ' before to enter register page.'),
( 'en', 'lang_labels', 'PAGE_NOT_FOUND', ' Page not found.'),
( 'en', 'lang_labels', 'START_SESSION', 'Start Session'),
( 'en', 'lang_labels', 'END_SESSION', 'End Session'),
( 'en', 'lang_labels', 'TITLE_END_REGISTER', 'Register - End'),
( 'en', 'lang_labels', 'TITLE_LOGIN', 'Start Session'),
( 'en', 'lang_labels', 'TITLE_LOGOUT', 'End Session'),
( 'en', 'lang_labels', 'TITLE_NEW_GALLERY', 'Create gallery or insert photos'),
( 'en', 'lang_labels', 'TITLE_SAVE_DATA', 'Save data'),
( 'es', 'lang_labels', 'FRM_YET_RECEIVED', 'El formulario ya se ha enviado. Los datos que intenta insertar ya fueron recibidos. Esto puede ocurrir al pulsar varias veces el botón de enviar, o al recargar la página tras enviar un formulario.'),
( 'en', 'lang_labels', 'FRM_YET_RECEIVED', 'The form you are trying to send was received already. This could happen when pressing twice the send button, or when reloading the page after form submitting.'),
( 'es', 'lang_labels', 'CAPTCHA_ERROR','El código captcha introducido no es correcto'),
( 'en', 'lang_labels', 'CAPTCHA_ERROR','The captcha code introduced is not correct'),
( 'es', '404.rep', 'replace_content', '<b>Opps</b> <p>La página que busca no se encuentra en este servidor, compruebe que ha escrito correctamente la dirección.</p>'),
( 'es', 'entrance.rep', 'replace_title', 'Entrada'),
( 'es', 'ficha.rep', '{h2_galleries}', 'Galerías'),
( 'es', 'ficha.rep', '{link_gallery}', 'gallery'),
( 'es', 'ficha.rep', '{go_friends}', 'Solicitar amistad'),
( 'es', 'frm_new_gallery.rep', 'replace_title', 'Crear nueva galería o insertar imágenes'),
( 'es', 'frm_new_gallery.rep', '{create_new_gallery}', 'Crear nueva galería'),
( 'es', 'frm_new_gallery.rep', '{gallery_name}', 'Nombre de la galería'),
( 'es', 'frm_new_gallery.rep', '{insert_name_gal}', 'Inserte el nombre de la galería de fotos'),
( 'es', 'frm_new_gallery.rep', '{placeholder_namegal}', 'Mi galería'),
( 'es', 'frm_new_gallery.rep', '{send_button}', 'Crear'),
( 'es', 'frm_new_gallery.rep', '{js_please_enter_galname}', 'Por favor, introduzca un nombre para la galería'),
( 'es', 'frm_new_gallery.rep', '{is_private}', 'Galería privada ( sólo pueden verla amigos )'),
( 'es', 'frm_new_gallery.rep', '{mark_if_private}', 'Marque esta casilla si la galería es privada, sólo la pueden ver amigos.'),
( 'es', 'frm_new_gallery.rep', '{name_passwd}', 'Contraseña ( Si introduce una contraseña, habrá que introducirla para ver la galería, incluso los amigos ).'),
( 'es', 'frm_new_gallery.rep', '{title_passwd}', 'Si introduce una contraseña, la galería sólo será visible para aquellos que la conozcan.'),
( 'es', 'frm_new_gallery.rep', '{js_max_100_chars}', 'El nombre de la galería tiene un máximo de 100 caracteres'),
( 'es', 'frm_new_gallery.rep', '{js_only_alphanum}', 'El nombre de la galería sólo puede contener caracteres alfanuméricos, y espacios'),
( 'es', 'frm_new_gallery.rep', '{js_max_40_chars}', 'La contraseña no puede tener más de 40 caracteres'),
( 'es', 'frm_new_gallery.rep', '{link_pictures_end}', 'grabar-datos'),
( 'es', 'frm_new_gallery.rep', '{insert_photos_in_gallery}', 'Subir fotos'),
( 'es', 'frm_new_gallery.rep', '{choose_gallery}', 'Escoger galería de destino'),
( 'es', 'frm_new_gallery.rep', '{send_photos_button}', 'Subir'),
( 'es', 'gallery.rep', '{gallery_title}', 'Galerías de'),
( 'es', 'gallery.rep', '{lbl_photos}', 'fotos'),
( 'es', 'gallery.rep', '{{not_allowed_to_see}}', 'No tiene autorización para ver esta galería.'),
( 'es', 'gallery.rep', '{h2_gal_protected}', 'Protegida por contraseña'),
( 'es', 'gallery.rep', '{p_gal_password}', 'Esta galería requiere una contraseña para verla.'),
( 'es', 'gallery.rep', '{passwd}', 'password'),
( 'es', 'gallery.rep', '{title_passwd}', 'Por favor inserte el password de la galería'),
( 'es', 'gallery.rep', '{send_button}', 'Entrar'),
( 'es', 'gallery.rep', '{js_please_enter_passwd}', 'Por favor, introduzca el password de la galería'),
( 'es', 'gallery.rep', '{js_max_40_chars}', 'El password no puede contener más de 40 caracteres'),
( 'es', 'gallery.rep', '{{no_photos}}', 'Esta galería aún no contiene fotos.'),
( 'es', 'header.rep', 'replace_search', 'Búsqueda'),
( 'es', 'header.rep', 'replace_your_account', 'Su Cuenta'),
( 'es', 'header.rep', 'replace_init_session', 'Iniciar Sesión'),
( 'es', 'header.rep', 'replace_close_session', 'Cerrar Sesión'),
( 'es', 'header.rep', 'replace_langlabel', 'Idioma'),
( 'es', 'header.rep', 'replace_lang_es', 'Español'),
( 'es', 'header.rep', 'replace_lang_en', 'Inglés'),
( 'es', 'header.rep', 'replace_lang_it', 'Italiano'),
( 'es', 'header.rep', 'replace_lang_fr', 'Francés'),
( 'es', 'header.rep', 'replace_menu_init', 'Home'),
( 'es', 'header.rep', 'replace_menu_register', 'Registro'),
( 'es', 'header.rep', 'replace_menu_legal', 'Aviso Legal'),
( 'es', 'header.rep', 'replace_menu_directory', 'Directorio'),
( 'es', 'header.rep', 'replace_menu_help', 'Ayuda'),
( 'es', 'header.rep', 'replace_menu_contact', 'Contacto'),
( 'es', 'header.rep', 'replace_link_home', 'replace_ff_url/replace_ff_lang/'),
( 'es', 'header.rep', 'replace_link_register', 'replace_ff_url/replace_ff_lang/registro/'),
( 'es', 'header.rep', 'replace_link_legal', 'replace_ff_url/replace_ff_lang/legal/'),
( 'es', 'header.rep', 'replace_link_directory', 'replace_ff_url/replace_ff_lang/directorio/'),
( 'es', 'header.rep', 'replace_link_help', 'replace_ff_url/replace_ff_lang/ayuda/'),
( 'es', 'header.rep', 'replace_link_contact', 'replace_ff_url/replace_ff_lang/contacto/'),
( 'es', 'header.rep', '{init_session}', 'Iniciar Sesión'),
( 'es', 'header.rep', '{end_session}', 'Salir'),
( 'es', 'header.rep', '{edit_profile}', 'Editar Perfil'),
( 'es', 'header.rep', '{link_edit_profile}', 'editar-perfil'),
( 'es', 'header.rep', '{replace_base_link}', 'replace_ff_url/replace_ff_lang'),
( 'es', 'header.rep', '{link_insert_gallery}', 'imagenes-y-galerias'),
( 'es', 'header.rep', '{add_photos}', 'Añadir fotos'),
( 'es', 'header.rep', '{insert_gallery}', 'Insertar Gallería'),
( 'es', 'login.rep', 'replace_title', 'Iniciar Sesión'),
( 'es', 'login.rep', '{login_h2}', 'Iniciar Sesión'),
( 'es', 'login.rep', '{link_login_end}', 'entrada'),
( 'es', 'login.rep', '{email_user}', 'E-mail'),
( 'es', 'login.rep', '{insert_email_user}', 'Por favor, inserte su e-mail'),
( 'es', 'login.rep', '{placeholder_email_user}', 'usuario@example.com'),
( 'es', 'login.rep', '{passwd}', 'password'),
( 'es', 'login.rep', '{title_passwd}', 'Por favor inserte su password'),
( 'es', 'login.rep', '{send_button}', 'Entrar'),
( 'es', 'login.rep', '{js_please_enter_email_user}', 'Debe introducir su e-mail'),
( 'es', 'login.rep', '{js_max_255_chars}', 'El e-mail tiene una longitud máxima de 255 caracteres'),
( 'es', 'login.rep', '{js_email}', 'Debe introducir un e-mail correcto'),
( 'es', 'login.rep', '{js_please_enter_passwd}', 'Por favor, introduzca su password'),
( 'es', 'login.rep', '{js_max_40_chars}', 'El password no puede contener más de 40 caracteres'),
( 'es', 'logout.rep', '{message_of_logout}', 'Sesión terminada. Gracias por utilizar nuestros servicios.'),
( 'es', 'pictures_end.rep', '{gal_name_max_100_chars}', 'El nombre de la galería tiene que ser como máximo de 100 caracteres.'),
( 'es', 'pictures_end.rep', '{gal_name_only_alphanum}', 'El nombre de la galería sólo puede contener caracteres alfanuméricos y espacios.'),
( 'es', 'pictures_end.rep', '{gallery_ok}', 'La galería se creó correctamente.'),
( 'es', 'pictures_end.rep', '{gallery_ko}', 'Hubo un error al insertar la galería. Si el problema persiste, póngase en contacto con los administradores.'),
( 'es', 'pictures_end.rep', '{no_data_received}', 'No se han recibido datos.'),
( 'es', 'pictures_end.rep', '{already_used_name_gallery}', 'Usted ya tiene una galería con el mismo nombre, utilice otro distinto, por favor.'),
( 'es', 'pictures_end.rep', '{no_files_uploaded}', 'No se subió ningún archivo.'),
( 'es', 'pictures_end.rep', '{files_uploaded_ok}', 'Archivos subidos.'),
( 'en', '404.rep', 'replace_content', '<b>Opps</b> <p>Page Not Found - The requested page could not be found.</p>'),
( 'en', 'entrance.rep', 'replace_title', 'Entrance'),
( 'en', 'ficha.rep', '{h2_galleries}', 'Galleries'),
( 'en', 'ficha.rep', '{link_gallery}', 'gallery'),
( 'en', 'ficha.rep', '{go_friends}', 'Go Friends'),
( 'en', 'frm_new_gallery.rep', 'replace_title', 'Create new gallery or insert images'),
( 'en', 'frm_new_gallery.rep', '{create_new_gallery}', 'Create new gallery'),
( 'en', 'frm_new_gallery.rep', '{gallery_name}', 'Gallery name'),
( 'en', 'frm_new_gallery.rep', '{insert_name_gal}', 'Insert the name of the photo gallery'),
( 'en', 'frm_new_gallery.rep', '{placeholder_namegal}', 'My gallery'),
( 'en', 'frm_new_gallery.rep', '{send_button}', 'Create'),
( 'en', 'frm_new_gallery.rep', '{js_please_enter_galname}', 'Please insert a name for the gallery'),
( 'en', 'frm_new_gallery.rep', '{is_private}', 'Private gallery ( only friends allowed )'),
( 'en', 'frm_new_gallery.rep', '{mark_if_private}', 'Mark this if the gallery is private, only friends are allowed to see it'),
( 'en', 'frm_new_gallery.rep', '{name_passwd}', 'Password ( If you enter a password, it will be required to see the gallery, even friends )'),
( 'en', 'frm_new_gallery.rep', '{title_passwd}', 'If you enter a password, the gallery it\'s only viewable by those who knows the password'),
( 'en', 'frm_new_gallery.rep', '{js_max_100_chars}', 'The name of the gallery has a maximum of 100 chars'),
( 'en', 'frm_new_gallery.rep', '{js_only_alphanum}', 'The name of the gallery can contain only alphanumeric characters and spaces'),
( 'en', 'frm_new_gallery.rep', '{js_max_40_chars}', 'The password must be max. 40 characters long'),
( 'en', 'frm_new_gallery.rep', '{link_pictures_end}', 'save-data'),
( 'en', 'frm_new_gallery.rep', '{insert_photos_in_gallery}', 'Upload photos'),
( 'en', 'frm_new_gallery.rep', '{choose_gallery}', 'Choose destination gallery'),
( 'en', 'frm_new_gallery.rep', '{send_photos_button}', 'Upload'),
( 'en', 'gallery.rep', '{gallery_title}', 'Galleries of'),
( 'en', 'gallery.rep', '{lbl_photos}', 'photos'),
( 'en', 'gallery.rep', '{{not_allowed_to_see}}', 'You are not allowed to see this gallery.'),
( 'en', 'gallery.rep', '{h2_gal_protected}', 'Password required'),
( 'en', 'gallery.rep', '{p_gal_password}', 'This gallery requires a password to see it.'),
( 'en', 'gallery.rep', '{passwd}', 'password'),
( 'en', 'gallery.rep', '{title_passwd}', 'Please insert the gallery password'),
( 'en', 'gallery.rep', '{send_button}', 'Enter'),
( 'en', 'gallery.rep', '{js_please_enter_passwd}', 'Please, insert the gallery password'),
( 'en', 'gallery.rep', '{js_max_40_chars}', 'Password is max. 40 characters long'),
( 'en', 'gallery.rep', '{{no_photos}}', 'This gallery no contains photos yet.'),
( 'en', 'header.rep', 'replace_search', 'Search'),
( 'en', 'header.rep', 'replace_your_account', 'Your Account'),
( 'en', 'header.rep', 'replace_init_session', 'Start Session'),
( 'en', 'header.rep', 'replace_close_session', 'End Session'),
( 'en', 'header.rep', 'replace_langlabel', 'Language'),
( 'en', 'header.rep', 'replace_lang_es', 'Spanish'),
( 'en', 'header.rep', 'replace_lang_en', 'English'),
( 'en', 'header.rep', 'replace_lang_it', 'Italian'),
( 'en', 'header.rep', 'replace_lang_fr', 'French'),
( 'en', 'header.rep', 'replace_menu_init', 'Home'),
( 'en', 'header.rep', 'replace_menu_register', 'Register'),
( 'en', 'header.rep', 'replace_menu_legal', 'Legal'),
( 'en', 'header.rep', 'replace_menu_directory', 'Directory'),
( 'en', 'header.rep', 'replace_menu_help', 'Help'),
( 'en', 'header.rep', 'replace_menu_contact', 'Contact'),
( 'en', 'header.rep', 'replace_link_home', 'replace_ff_url/replace_ff_lang/'),
( 'en', 'header.rep', 'replace_link_register', 'replace_ff_url/replace_ff_lang/register/'),
( 'en', 'header.rep', 'replace_link_legal', 'replace_ff_url/replace_ff_lang/legal/'),
( 'en', 'header.rep', 'replace_link_directory', 'replace_ff_url/replace_ff_lang/directory/'),
( 'en', 'header.rep', 'replace_link_help', 'replace_ff_url/replace_ff_lang/help/'),
( 'en', 'header.rep', 'replace_link_contact', 'replace_ff_url/replace_ff_lang/contact/'),
( 'en', 'header.rep', '{init_session}', 'Start Session'),
( 'en', 'header.rep', '{end_session}', 'End Session'),
( 'en', 'header.rep', '{edit_profile}', 'Edit Profile'),
( 'en', 'header.rep', '{link_edit_profile}', 'edit-profile'),
( 'en', 'header.rep', '{replace_base_link}', 'replace_ff_url/replace_ff_lang'),
( 'en', 'header.rep', '{link_insert_gallery}', 'images-and-galleries'),
( 'en', 'header.rep', '{add_photos}', 'Add photos'),
( 'en', 'header.rep', '{insert_gallery}', 'Insert Gallery'),
( 'en', 'header.rep', '{improve_position}', 'Improve position'),
( 'en', 'header.rep', '{buy_banner}', 'Buy banner'),
( 'en', 'login.rep', 'replace_title', 'Start session'),
( 'en', 'login.rep', '{login_h2}', 'Start Session'),
( 'en', 'login.rep', '{link_login_end}', 'entrance'),
( 'en', 'login.rep', '{email_user}', 'E-mail'),
( 'en', 'login.rep', '{insert_email_user}', 'Please insert your e-mail'),
( 'en', 'login.rep', '{placeholder_email_user}', 'user@example.com'),
( 'en', 'login.rep', '{passwd}', 'password'),
( 'en', 'login.rep', '{title_passwd}', 'Please enter your password'),
( 'en', 'login.rep', '{send_button}', 'Login'),
( 'en', 'login.rep', '{js_please_enter_email_user}', 'You must enter your e-mail'),
( 'en', 'login.rep', '{js_max_255_chars}', 'The e-mail must be max. 255 characters long'),
( 'en', 'login.rep', '{js_email}', 'You must enter a valid e-mail'),
( 'en', 'login.rep', '{js_please_enter_passwd}', 'Please enter your password'),
( 'en', 'login.rep', '{js_max_40_chars}', 'Password must be maximum 40 chars long'),
( 'en', 'logout.rep', '{message_of_logout}', 'Session finished. Thanks for using our services.'),
( 'en', 'pictures_end.rep', '{gal_name_max_100_chars}', 'The name of the gallery is 100 chars long as maximum.'),
( 'en', 'pictures_end.rep', '{gal_name_only_alphanum}', 'The gallery name can contains only alphanumeric characters and spaces.'),
( 'en', 'pictures_end.rep', '{gallery_ok}', 'The gallery was inserted.'),
( 'en', 'pictures_end.rep', '{gallery_ko}', 'There was an error inserting the gallery. If the problem persists, contact the page administrators.'),
( 'en', 'pictures_end.rep', '{no_data_received}', 'No data received.'),
( 'en', 'pictures_end.rep', '{already_used_name_gallery}', 'You have a gallery with the same name already, please use another name.'),
( 'en', 'pictures_end.rep', '{no_files_uploaded}', 'No files were uploaded.'),
( 'en', 'pictures_end.rep', '{files_uploaded_ok}', 'Files uploaded.'),
( 'es', 'become_friends', '{go_friends}', 'Amistad aceptada, ahora eres amigo de'),
( 'es', 'become_friends', '{friendship_requested}', 'Solicitud pendiente. Se ha enviado una solicitud de amistad a'),
( 'es', 'become_friends', '{mail_1}', 'El usuario'),
( 'es', 'become_friends', '{mail_2}', 'le ha enviado una solicitud de amistad en'),
( 'es', 'become_friends', '{some_error}', 'Ha ocurrido un error al intentar realizar la operación. Por favor, inténtelo en unos minutos, o póngase en contacto con nosotros escribiendo a <a href="mailto:{replace_contact_mail}?subject=error al registrar amistad">{replace_contact_mail}</a>'),
( 'es', 'become_friends', '{yet_solicited}', 'Ya solicitado. Ya existe una solicitud pendiente de amistad con este usuario, debe esperar usted a que el usuario responda.'),
( 'es', 'become_friends', '{already_friends_1}', 'No se puede solicitar de nuevo esta amistad, porque usted y'),
( 'es', 'become_friends', '{already_friends_2}', 'ya son amigos en la actualidad.'),
( 'es', 'become_friends', '{mail_3}', 'Solicitud de amistad'),
( 'es', 'become_friends', '{code_refused}', 'El código de su formulario no es correcto. Si el problema persiste, contacte con nosotros escribiendo a <a href="mailto:{replace_contact_mail}?subject=error de codigo de formulario">{replace_contact_mail}</a>'),
( 'en', 'become_friends', '{go_friends}', 'Accepted friendship. Now you are friend of'),
( 'en', 'become_friends', '{friendship_requested}', 'Pending friendship. Request sent to'),
( 'en', 'become_friends', '{mail_1}', 'The user'),
( 'en', 'become_friends', '{mail_2}', 'want to be your friend in'),
( 'en', 'become_friends', '{some_error}', 'An error occurred. Please try again in some minutes, or contact with us in <a href="mailto:{replace_contact_mail}?subject=error registering frindship ">{replace_contact_mail}</a>'),
( 'en', 'become_friends', '{yet_solicited}', 'Already requested. You have asked for friendship, you must wait for this user response.'),
( 'en', 'become_friends', '{already_friends_1}', 'Cannot request this friendship, as you and'),
( 'en', 'become_friends', '{already_friends_2}', 'are already friends.'),
( 'en', 'become_friends', '{mail_3}', 'Friendship request'),
( 'en', 'become_friends', '{code_refused}', 'The code of your form is invalid. If the problem persists, please contact us in <a href="mailto:{replace_contact_mail}?subject=form code error">{replace_contact_mail}</a>'),
( 'en', 'header.rep', '{user_not_found}', 'User not found'),
( 'es', 'header.rep', '{user_not_found}', 'Usuario no encontrado'),
( 'es', 'header.rep', '{galleries_of}', 'Galerías de'),
( 'en', 'header.rep', '{galleries_of}', 'Galleries of'),
( 'es', 'header.rep', '{personal_data}', 'Datos personales'),
( 'es', 'header.rep', '{other_data}', 'Otros Datos'),
( 'es', 'header.rep', '{description}', 'Descripción'),
( 'en', 'header.rep', '{personal_data}', 'Personal Data'),
( 'en', 'header.rep', '{other_data}', 'Other Data'),
( 'en', 'header.rep', '{description}', 'Description'),
( 'es', 'header.rep', '{friends_title}', 'Amigos'),
( 'es', 'header.rep', '{friendship_requests_title}', 'Solicitudes'),
( 'es', 'header.rep', '{messages_title}', 'Mensajes'),
( 'es', 'header.rep', '{last_connection}', 'Último acceso'),
( 'en', 'header.rep', '{friends_title}', 'Friends'),
( 'en', 'header.rep', '{friendship_requests_title}', 'Requests'),
( 'en', 'header.rep', '{messages_title}', 'Messages'),
( 'en', 'header.rep', '{last_connection}', 'Last access'),
( 'es', 'header.rep', '{lbl_include_friend}', 'Aceptar solicitud de amistad de '),
( 'en', 'header.rep', '{lbl_include_friend}', 'Accept friendship request from '),
( 'es', 'header.rep', '{no_friendship_requests}', 'No hay solicitudes de amistad'),
( 'en', 'header.rep', '{no_friendship_requests}', 'No friendship requests'),
( 'en', 'header.rep', '{confirm}', 'Confirm'),
( 'es', 'header.rep', '{confirm}', 'Confirmar'),

( 'es', 'js_validation', 'required', 'Este campo no puede estar vac&iacute;o.'),
( 'es', 'js_validation', 'email', 'El e-mail no es correcto.'),
( 'es', 'js_validation', 'alphanum', 'Debe usar s&oacute;lo caracteres alfanum&eacute;ricos (a-z 0-9) y _ .'),
( 'es', 'js_validation', 'alphanumex', "Puede usar s&oacute;lo caracteres alfanum&eacute;ricos (a-z 0-9)  así como acentos y diéresis, y los caracteres: _-'."),
( 'es', 'js_validation', 'bad_chars', 'El campo contiene caracteres no permitidos.'),
( 'es', 'js_validation', 'only_numeric', 'Este campo s&oacute;lo puede contener n&uacute;meros.'),
( 'es', 'js_validation', 'only_integer', 'Este campo s&oacute;lo puede contener n&uacute;meros enteros.'),
( 'es', 'js_validation', 'not_enough_chars', 'El dato introducido es demasiado corto. M&iacute;nimo rpl_param caracteres.'),
( 'es', 'js_validation', 'too_much_chars', 'El dato introducido es demasiado largo. M&aacute;ximo rpl_param caracteres.'),
( 'es', 'js_validation', 'bad_date', 'La fecha introducida no es correcta o no es v&aacute;lida.'),
( 'es', 'js_validation', 'not_equals_to', 'El valor debe coincidir con el anterior'),
( 'es', 'js_validation', 'min_value', 'El valor introducido debe ser por lo menos rpl_param.'),
( 'es', 'js_validation', 'max_value', 'El valor introducido debe ser como m&aacute;ximo rpl_param.'),
( 'es', 'js_validation', 'url', 'La url introducida no es v&aacute;lida.'),
( 'es', 'js_validation', 'internal_error', 'Error interno: No existe el caso de validaci&oacute;n: rpl_param. Por favor contacte con el webmaster.'),
( 'es', 'js_validation', 'yet_registered_nick', 'El nombre de usuario ya está en uso.'),
( 'es', 'js_validation', 'yet_registered_mail', 'El e-mail ya está en uso.'),
( 'es', 'js_validation', 'image_formats', 'jpg, png, gif'),
( 'es', 'js_validation', 'image_file_button_text', 'Imagen'),

( 'en', 'js_validation', 'required', 'This field cannot be empty'),
( 'en', 'js_validation', 'email', 'Please correct the e-mail'),
( 'en', 'js_validation', 'alphanum', 'Use only alphanumeric characters (a-z 0-9) and _ .'),
( 'en', 'js_validation', 'alphanumex', "Use only alphanumeric characters (a-z 0-9) and accentued letters and dieresis, and following chars: _-'. "),
( 'en', 'js_validation', 'bad_chars', 'The field has not allowed characters.'),
( 'en', 'js_validation', 'only_numeric', 'This field can contain only numbers.'),
( 'en', 'js_validation', 'only_integer', 'This field can contain only integer numbers.'),
( 'en', 'js_validation', 'not_enough_chars', 'Data is too short. rpl_param characters minimum.'),
( 'en', 'js_validation', 'too_much_chars', 'Data is too large. rpl_param characters maximum.'),
( 'en', 'js_validation', 'bad_date', "Date introduced is not correct, or it's invalid."),
( 'en', 'js_validation', 'not_equals_to', 'Value must be the same as precedent field'),
( 'en', 'js_validation', 'min_value', 'Value must be at least rpl_param.'),
( 'en', 'js_validation', 'max_value', 'Maximum value is rpl_param.'),
( 'en', 'js_validation', 'url', 'Not valid url.'),
( 'en', 'js_validation', 'internal_error', "Internal error: Validation case doesn't exist: rpl_param. Please contact us about this error."),
( 'en', 'js_validation', 'yet_registered_nick', 'The user nick is already registered.'),
( 'en', 'js_validation', 'yet_registered_mail', 'The e-mail is already registered.'),
( 'en', 'js_validation', 'image_formats', 'jpg, png, gif'),
( 'en', 'js_validation', 'image_file_button_text', 'Image');

